name: keycloak_wrapper
description: MyDigital ID Keycloak Single Sign-On (SSO) authentication package for Flutter framework.

screenshots:
  - description: "Default Keycloak Login Screen"
    path: screenshots/login-screen.png
topics: [ authentication, keycloak, oauth2, openidconnect ]

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.0+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: